name: Football Notifications

on:
  schedule:
    - cron: "0 21 * * *"

  workflow_dispatch:

jobs:
  send-matches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          API_KEY: ${{ secrets.KEY }}
          BOT_TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python work.py